'use client';

import { useState } from 'react';
import { Download, FileText, Copy, FileDown, Check } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import type { BurnoutReport } from '@/services/github/burnout-analyzer';
import jsPDF from 'jspdf';

export default function DownloadReportMenu({ report }: { report: BurnoutReport }) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    const date = new Date().toLocaleDateString();
    let md = `# Team Health Report: ${report.repoName}\n\n`;
    md += `**Analysis Date:** ${date}\n\n`;
    md += `## Overall Risk: ${report.dependencyRisk}\n\n`;
    md += `### Key Findings:\n`;

    if (report.contributors.length > 0) {
      const topCount = Math.min(2, report.contributors.length);
      const topShare = report.contributors
        .slice(0, topCount)
        .reduce((acc, c) => acc + c.commitShare, 0);
      md += `- ${topCount} contributors handled ${Math.round(topShare)}% of recent commits.\n`;
    }

    const inactiveCount = report.inactivityAlerts.length;
    if (inactiveCount > 0) {
      md += `- ${inactiveCount} core contributor(s) have been inactive for recent weeks.\n`;
    }

    const overloadedCount = report.contributors.filter((c) => c.riskLevel === 'High').length;
    if (overloadedCount > 0) {
      md += `- Review/maintenance load appears concentrated (${overloadedCount} contributor(s) at high risk).\n`;
    } else {
      md += `- Maintenance load is fairly distributed among active contributors.\n`;
    }

    md += `\n### Recommendations:\n`;
    if (report.recommendations.length > 0) {
      report.recommendations.forEach((rec) => {
        const cleanRec = rec.replace('[AI Recommendation] ', '');
        md += `- ${cleanRec}\n`;
      });
    } else {
      md += `- No specific recommendations at this time.\n`;
    }

    md += `\n---\n*Generated by CommitPulse Burnout Radar*`;
    return md;
  };

  const handleDownloadMd = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.repoName.replace('/', '-')}-health-report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const handleCopySummary = async () => {
    const md = generateMarkdown();
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => {
      setCopied(false);
      setIsOpen(false);
    }, 2000);
  };

  const handleDownloadPdf = () => {
    const md = generateMarkdown();
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text(`Team Health Report: ${report.repoName}`, 10, 20);
    doc.setFontSize(12);
    const lines = doc.splitTextToSize(md, 180);
    doc.text(lines, 10, 30);
    doc.save(`${report.repoName.replace('/', '-')}-health-report.pdf`);
    setIsOpen(false);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white rounded-xl text-sm font-medium transition-colors shadow-sm active:scale-95"
      >
        <Download size={16} />
        <span className="hidden sm:inline">Download Report</span>
        <span className="sm:hidden">Report</span>
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.95 }}
            transition={{ duration: 0.15 }}
            className="absolute right-0 mt-2 w-56 bg-white dark:bg-[#111] border border-black/10 dark:border-white/10 rounded-xl shadow-lg overflow-hidden z-50"
          >
            <div className="p-1 flex flex-col">
              <button
                onClick={handleDownloadMd}
                className="flex items-center gap-2 px-3 py-2.5 text-sm font-medium text-gray-700 dark:text-zinc-300 hover:bg-gray-100 dark:hover:bg-white/5 rounded-lg transition-colors text-left"
              >
                <FileText size={16} className="text-gray-400" />
                Download as Markdown
              </button>
              <button
                onClick={handleDownloadPdf}
                className="flex items-center gap-2 px-3 py-2.5 text-sm font-medium text-gray-700 dark:text-zinc-300 hover:bg-gray-100 dark:hover:bg-white/5 rounded-lg transition-colors text-left"
              >
                <FileDown size={16} className="text-gray-400" />
                Download as PDF
              </button>
              <button
                onClick={handleCopySummary}
                className="flex items-center gap-2 px-3 py-2.5 text-sm font-medium text-gray-700 dark:text-zinc-300 hover:bg-gray-100 dark:hover:bg-white/5 rounded-lg transition-colors text-left"
              >
                {copied ? (
                  <Check size={16} className="text-emerald-500" />
                ) : (
                  <Copy size={16} className="text-gray-400" />
                )}
                {copied ? 'Copied!' : 'Copy Summary'}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {isOpen && <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />}
    </div>
  );
}
