blank_issues_enabled: false
contact_links:
  - name: Ask a question or get support
    url: https://discord.gg/f84SDraEBH
    about: Please join our Discord server for general questions instead of opening an issue.
