import { encryptToken, decryptToken } from './crypto';
// import crypto from 'node:crypto';

export interface DecryptedToken {
  token: string;
  nextIndex: number;
}

export interface EncryptedTokenData {
  token: string;
  encryptedToken: string;
  rotationIndex: number;
}

/**
 * Encrypt GitHub token for storage using AES-256-GCM.
 * @param token - GitHub PAT or token
 * @returns Encrypted token payload
 */
export function encryptGitHubToken(token: string): string {
  if (!token || typeof token !== 'string') {
    throw new Error('Invalid GitHub token');
  }

  try {
    return encryptToken(token);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Token encryption failed: ${message}`);
  }
}

/**
 * Decrypt GitHub token payload generated by encryptGitHubToken().
 * @param encryptedToken - AES-256-GCM encrypted payload
 * @returns Decrypted GitHub token
 */
export function decryptGitHubToken(encryptedToken: string): string {
  try {
    return decryptToken(encryptedToken);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Token decryption failed: ${message}`);
  }
}

/**
 * Parse comma-separated tokens and return encrypted array.
 * Handles legacy comma-separated format and encrypts each token.
 * @param tokenString - Comma-separated tokens or single token
 * @returns Array of {token: string, encryptedToken: string}
 */
export function parseAndEncryptTokens(tokenString: string): EncryptedTokenData[] {
  if (!tokenString || typeof tokenString !== 'string') {
    throw new Error('Token string is required');
  }

  const tokens = tokenString
    .split(',')
    .map((t) => t.trim())
    .filter((t) => t.length > 0);

  if (tokens.length === 0) {
    throw new Error('No valid tokens found');
  }

  // Validate token format (should start with ghp_ or ghu_)
  for (const token of tokens) {
    if (!token.startsWith('ghp_') && !token.startsWith('ghu_')) {
      console.warn(`Token does not appear to be valid GitHub PAT: ${token.substring(0, 5)}...`);
    }
  }

  return tokens.map((token, index) => ({
    token,
    encryptedToken: encryptGitHubToken(token),
    rotationIndex: index,
  }));
}

/**
 * Get next GitHub token from encrypted rotation list.
 * Used to rotate tokens and distribute rate limits.
 * @param encryptedTokens - Array of encrypted tokens
 * @param currentIndex - Current rotation index
 * @returns {token: string, nextIndex: number}
 */
export function getNextToken(encryptedTokens: string[], currentIndex = 0): DecryptedToken {
  if (!Array.isArray(encryptedTokens) || encryptedTokens.length === 0) {
    throw new Error('No encrypted tokens available');
  }

  const nextIndex = (currentIndex + 1) % encryptedTokens.length;
  const encryptedToken = encryptedTokens[nextIndex];

  return {
    token: decryptGitHubToken(encryptedToken),
    nextIndex,
  };
}

/**
 * Validate that a token is properly encrypted.
 * @param encryptedToken - Token to validate
 * @returns True if token appears to be encrypted
 */
export function isEncryptedToken(encryptedToken: string | null | undefined): boolean {
  if (!encryptedToken || typeof encryptedToken !== 'string') {
    return false;
  }

  return encryptedToken.split('.').length === 4;
}

/**
 * CRITICAL: Never log or expose full GitHub tokens.
 * Logging utility that safely redacts tokens.
 * @param token - Token to redact for logging
 * @returns Redacted token for safe logging
 */
export function redactToken(token: string | null | undefined): string {
  if (!token || token.length < 10) {
    return '***';
  }

  const start = token.substring(0, 4);
  const end = token.substring(token.length - 4);
  return `${start}...${end}`;
}
